version: "3.4"
services:
  web:
    restart: on-failure
    image: ghcr.io/dimaip/oktbot:main
    hostname: 'oktBot'
    networks:
      - main
    environment:
      - TOKEN
      - CHANNEL_ID
    ports:
      - '80'
networks:
  main:
    external:
      name: main
